server:
  port: 8080

spring:
  datasource:
    name: tasks
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

# Actuator endpoints
management:
  security:
    enbled: false